chore: Centralize Status Management
canonical/sdcore-pcf-k8s-operator pull request #89
Opened 2024-03-13 13:27 UTC by gatici

# Description

This PR uses new ops feature CollectStatus Event to manage status Charm. Event named collect_unit_status sets the status of charm automatically at the end of every hook.

Reference:

    https://ops.readthedocs.io/en/latest/#ops.CollectStatusEvent
    https://discourse.charmhub.io/t/how-to-set-a-charms-status/11771

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2024-03-13 13:48 UTC, ghislainbourgeois requested changes

2024-03-13 13:48 UTC, ghislainbourgeois commented on src/charm.py
> +            # teardown code is necessary to preform if we're removing the
```suggestion
            # teardown code is necessary to perform if we're removing the
```

2024-03-14 08:49 UTC, gatici commented on src/charm.py
> +            # teardown code is necessary to preform if we're removing the
Done

2024-03-14 14:41 UTC, ghislainbourgeois approved these changes

2024-03-14 14:57 UTC, merged